### ISSUE TITLE
Inadequate performance on Linux (~40 FPS)

### ISSUE THREAD

**Issue by brandon-arnold** [DerKoun/bsnes-hd#110]
Hi all. Thanks for the great work on bsnes-hd! I just tried the [VitorVilela7](https://github.com/VitorVilela7)/[wide-snes](https://github.com/VitorVilela7/wide-snes) hack for SMW on a beefy machine. It hardly kept up on the title screen, dropping to 40 FPS and skipping music. But I have basically perfect performance running it within Windows on a much lower-powered machine (the Aya Neo Pro).

This is a Dell XPS 17 (9700), which has both a dedicated NVIDIA and an integrated Intel GPU I can switch between using NVIDIA Optimus drivers. I tried both graphics cards with identical results. Perhaps bsnes-hd is not using much hardware acceleration in Linux?

**Comment by poudink** [comment]
This isn't Linux specific, hardware acceleration's just not much of a thing in this. Your CPU's doing all of the heavy lifting, that's why the readme lists "OpenGL/Vulkan" in its Help Wanted section. I just tried the widescreen mod and my shitty laptop's not really having any trouble running it full speed on Linux. It's got a dual core 2.6GHz AMD CPU with integrated graphics, definitely way worse than an XPS. There's probably just something in your configuration you overlooked. It can heavily affect your performance.
[settings.bml.zip](https://github.com/DerKoun/bsnes-hd/files/8458248/settings.bml.zip)
This is my configuration file, for reference.

**Comment by DerKoun** [comment]
This looks more like a support request than an issue. Could you join the Discord (see [readme](https://github.com/DerKoun/bsnes-hd#bsnes-hd-beta-106))? Should be easier to help you there. If so, please close this issue.

**Comment by brandon-arnold** [comment]
And thanks for sharing your settings and information, @poudink. I took a look and changed a couple of things on my end to match, but did not have different results. Weird!

@DerKoun Will join the Discord.
