### ISSUE TITLE
RetroArch 1.9.0: Where'd bsnes-hd go?

### ISSUE THREAD

**Issue by IngwiePhoenix** [DerKoun/bsnes-hd#56]
I know that some of the features were merged upstream regarding HD Mode 7, but the widescreen option is missing from that. So I went and tried to find the bsnes-hd core in the Core Downloader, but it was gone.

Any particular reason for that?

**Comment by DerKoun** [comment]
The Retroarch core versions for some systems, incl. Windows, seem to be gone since Libretro/Retroarch recovered from being hacked.
I'll talk to them and see if this can be solved from their or my side.
Until then I can only direct you to the standalone version.

**Comment by DerKoun** [comment]
_Same info I put on Discord:_
The bsnes-hd beta Retroarch core is currently unavailable for Windows and maybe other systems.
This is due to the Libretro team suffering a hacker attack some time ago that is still having effects. They are in the process of setting up an entirely new build system. 
I'll update you here when the core is available again

**Comment by DerKoun** [comment]
This has been solved some time ago. With the release of beta 10.4 I consider this issue solved.
@IngwiePhoenix please confirm

**Comment by IngwiePhoenix** [comment]
![image](https://user-images.githubusercontent.com/2893716/108612812-47dbdf00-73ec-11eb-8390-9c775b081051.png)
👍
