### ISSUE TITLE
[Question] Can I turn hd mode 7 off?

### ISSUE THREAD

**Issue by Toadfield** [DerKoun/bsnes-hd#92]
Some games run bad on my pc with hd mode 7,so I sometimes want to turn it off.
The problem is that when I change the hd mode 7 resolution to something lower,that then the whole game is rendered in that low resolution.
I also don't want to switch to normal bsnes,cause I want widescreen and hd mode 7 works for many games.
And also,can I set hd mode 7 to something lower than the other ingame resolution.

**Comment by DerKoun** [comment]
No, sorry, the scale is linked directly to HD Mode 7. I can put it on the to-do list to change that, but it's non-trivial. Much more so if you want resolutions larger than 1x but smaller than the output.
What features exactly are you using, that the higher scale has relevant benefits with Mode 7 being low-res?
Are you asking because of performance, or for visual/artistic reasons?

**Comment by Toadfield** [comment]
>Are you asking because of performance

yes

**Comment by DerKoun** [comment]
What features exactly are you using, that the higher scale has relevant benefits with Mode 7 being low-res?

**Comment by Toadfield** [comment]
That the non hd-mode-7 things have the resolution that my monitor has and therefore look the best.
I want that hd-mode-7 has a lower resolution cause it would cost less performance then,cause I also use run-ahead and therefore I can't use hd-mode-7 with a high resolution.

**Comment by DerKoun** [comment]
Just use nearest neighbor and integer scaling and you'll get the same result.
In standalone that's Settings/Output/Center and Settings/Shader/None. (Scale 1x)
RetroArch can do the same.

**Comment by DerKoun** [comment]
I'll close this, as there is no need for change.
I can explain further, but preferably on Discord.
