### ISSUE TITLE
-

### ISSUE THREAD

**Issue by hazelnot** [DerKoun/bsnes-hd#98]
-

**Comment by DerKoun** [comment]
Reported.
I won't be slandered for providing people a space to grieve.

**Comment by spacekookie** [comment]
@DerKoun I don't think you undestand slander. Just close the issue and move on instead of renaming it and editing the comment? Kind of a dick thing to do

**Comment by DerKoun** [comment]
"Libel" then.
I have been accused of something really bad, for no real reason, but for trying to give people a safe channel to grieve.
I'm trying to stay calm, because I assume hazelnot is also grieving, but unable to handle it in a non-aggressive way.
But I won't just take this.
If this gets removed and stops I'll do nothing more about it.
